Update VideoPlayerResolver.cs
Fix for the following error seen in 1.6.0-beta.6

Packages\net.kwxxw.yama-stream\Editor\Common\VideoPlayerResolver.cs(68,21): error CS1061: 'MediaPlayer.OptionsWindows' does not contain a definition for '_audioMode' and no accessible extension method '_audioMode' accepting a first argument of type 'MediaPlayer.OptionsWindows' could be found (are you missing a using directive or an assembly reference?)